linters:
  enable-all: true
  disable:
    - exhaustivestruct
    - paralleltest
    - varnamelen
    # deprecated
    - golint
    - maligned
    - interfacer
    - scopelint
    # error wrap
    - errorlint
    - goerr113
    - wrapcheck

linters-settings:
  govet:
    check-shadowing: true
  gofumpt:
    extra-rules: true
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - cyclop
        - funlen
        - gocognit
    - path: doc_test\.go
      linters:
        - gocritic
      text: "dupArg:"
