linters:
  enable-all: true
  disable:
    - paralleltest
    - varnamelen
    # deprecated
    - deadcode
    - exhaustivestruct
    - golint
    - ifshort
    - interfacer
    - maligned
    - nosnakecase
    - scopelint
    - structcheck
    - varcheck
    # error wrap
    - errorlint
    - goerr113
    - wrapcheck

linters-settings:
  depguard:
    rules:
      main:
        files:
          - $all
          - "!$test"
        allow:
          - $gostd
      test:
        files:
          - $test
        allow:
          - $gostd
          - github.com/sg0hsmt/goversion
  govet:
    check-shadowing: true
  gofumpt:
    extra-rules: true
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - cyclop
        - exhaustruct
        - funlen
        - gocognit
    - path: doc_test\.go
      linters:
        - gocritic
      text: "dupArg:"
