linters:
  enable-all: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - gocognit
        - goerr113
        - gomnd
        - scopelint
    - path: doc_test\.go
      linters:
        - lll
