name: Test
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:
permissions:
  contents: read
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.11.x, 1.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    env:
      GO111MODULE: on
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: go test -race -coverprofile="coverage.txt" -covermode=atomic
      - name: Upload coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          name: go${{ matrix.go-version }}, ${{ matrix.platform }}
